// server.js
// Main backend file for Student Notes Management System

// Load environment variables from .env file
require("dotenv").config();

const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");

// Import the Note model
const Note = require("./models/Note");

// Create Express app
const app = express();

// ─── MIDDLEWARE ───────────────────────────────────────────────
// Allow requests from frontend (CORS)
app.use(cors());

// Parse incoming JSON request bodies
app.use(express.json());

// ─── CONNECT TO MONGODB ATLAS ─────────────────────────────────
mongoose
  .connect(process.env.MONGO_URI)
  .then(() => {
    console.log("✅ Connected to MongoDB Atlas successfully!");
  })
  .catch((error) => {
    console.log("❌ MongoDB connection failed:", error.message);
  });

// ─── API ROUTES ───────────────────────────────────────────────

// 1. GET /notes → Fetch all notes from database
app.get("/notes", async (req, res) => {
  try {
    console.log("📥 GET /notes - Fetching all notes...");

    // Get all notes, sorted by newest first
    const notes = await Note.find().sort({ date: -1 });

    console.log(`✅ Found ${notes.length} notes`);
    res.json(notes);
  } catch (error) {
    console.log("❌ Error fetching notes:", error.message);
    res.status(500).json({ message: "Server error while fetching notes" });
  }
});

// 2. POST /notes → Add a new note to database
app.post("/notes", async (req, res) => {
  try {
    console.log("📤 POST /notes - Adding new note...");

    const { title, description } = req.body;

    // Basic validation
    if (!title || !description) {
      return res
        .status(400)
        .json({ message: "Title and description are required" });
    }

    // Create new note using our model
    const newNote = new Note({
      title: title,
      description: description,
      // date is auto-generated by the schema
    });

    // Save note to MongoDB
    const savedNote = await newNote.save();

    console.log("✅ Note added:", savedNote.title);
    res.status(201).json(savedNote);
  } catch (error) {
    console.log("❌ Error adding note:", error.message);
    res.status(500).json({ message: "Server error while adding note" });
  }
});

// 3. DELETE /notes/:id → Delete a note by its ID
app.delete("/notes/:id", async (req, res) => {
  try {
    const noteId = req.params.id;
    console.log(`🗑️ DELETE /notes/${noteId} - Deleting note...`);

    // Find note by ID and delete it
    const deletedNote = await Note.findByIdAndDelete(noteId);

    if (!deletedNote) {
      return res.status(404).json({ message: "Note not found" });
    }

    console.log("✅ Note deleted:", deletedNote.title);
    res.json({ message: "Note deleted successfully" });
  } catch (error) {
    console.log("❌ Error deleting note:", error.message);
    res.status(500).json({ message: "Server error while deleting note" });
  }
});

// ─── START SERVER ─────────────────────────────────────────────
const PORT = process.env.PORT || 5000;

app.listen(PORT, () => {
  console.log(`🚀 Server is running on http://localhost:${PORT}`);
  console.log(`📝 Student Notes Management System - Backend Ready`);
});
